docker run -it -d \
  --label traefik.http.routers.greengalaxyinvestments.rule=Host\(\`greengalaxyinvestments.buildcore.site\`\) \
  --label traefik.http.routers.greengalaxyinvestments.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.greengalaxyinvestments.tls=true \
  --label traefik.http.routers.greengalaxyinvestments.service=greengalaxyinvestments-credit-http \
  --label traefik.http.services.greengalaxyinvestments-credit-http.loadbalancer.server.port=80 \
  --name greengalaxyinvestments \
  --network web \
  --restart always \
  --expose 80 \
  ubuntu:latest